"""Prompt templates for LangGraph agents."""
from .analyst_prompts import (
    DOCUMENT_ANALYST_SYSTEM_PROMPT,
    ANALYST_USER_PROMPT_TEMPLATE,
    SHARED_DOCUMENT_CONTRIBUTION_TEMPLATE,
    SYNTHESIS_SYSTEM_PROMPT,
    SYNTHESIS_USER_PROMPT_TEMPLATE
)

__all__ = [
    "DOCUMENT_ANALYST_SYSTEM_PROMPT",
    "ANALYST_USER_PROMPT_TEMPLATE",
    "SHARED_DOCUMENT_CONTRIBUTION_TEMPLATE",
    "SYNTHESIS_SYSTEM_PROMPT",
    "SYNTHESIS_USER_PROMPT_TEMPLATE"
]
